server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: core
    default-schema: core
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.validation: TRACE

management:
  endpoints:
    web:
      exposure:
        include: mappings



